# Generated by Django 3.1.4 on 2021-09-29 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=100)),
                ('numero_telefone', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pedido_key', models.CharField(max_length=200)),
                ('status_pagamento', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-criado',),
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_items', to='store.produto')),
            ],
        ),
    ]
